[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "OracleTeam"
name = "CanadianCuisine"
description = "Adds Canadian foods and snacks fatefully rendered in the PEAK style."
websiteUrl = "https://github.com/MiiMii1205/CanadianCuisine"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_PEAK = "5.4.2403"
PEAKModding-PEAKLib_Items = "1.5.3"
MonoDetour-MonoDetour_BepInEx_5 = "0.6.7"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/CanadianCuisine/release/com.github.MiiMii1205.CanadianCuisine.dll"
target = "plugins/"

[[build.copy]]
source = "../../src/CanadianCuisine/bundles"
target = "plugins/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../src/CanadianCuisine/CanadianCuisineLocalizedText.csv"
target = "plugins/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "peak", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/peak/category/
peak = [ "mods", ]
